#!/bin/csh 
#$ -M cschaef6@nd.edu 
#$ -m abe
#$ -q gpu@@joshi
#$ -l gpu_card=1
#$ -N fl_test_checkpoint_9b3bc513-e21f-4399-bae9-8220b32e2884_0
#$ -o ./logs/output_fl_test_fl_test_checkpoint_9b3bc513-e21f-4399-bae9-8220b32e2884_0.txt
#$ -e ./logs/error_fl_test_fl_test_checkpoint_9b3bc513-e21f-4399-bae9-8220b32e2884_0.txt
module load python
setenv OMP_NUM_THREADS $NSLOTS
python test.py --checkpoint 9b3bc513-e21f-4399-bae9-8220b32e2884
