#!/bin/csh 
#$ -M cschaef6@nd.edu 
#$ -m abe
#$ -q gpu@@joshi
#$ -l gpu_card=1
#$ -N fl_test_checkpoint_2705f28d-5cf7-4b4e-8c4a-d1eeeee7108f_0
#$ -o ./logs/output_fl_test_fl_test_checkpoint_2705f28d-5cf7-4b4e-8c4a-d1eeeee7108f_0.txt
#$ -e ./logs/error_fl_test_fl_test_checkpoint_2705f28d-5cf7-4b4e-8c4a-d1eeeee7108f_0.txt
module load python
setenv OMP_NUM_THREADS $NSLOTS
python test.py --checkpoint 2705f28d-5cf7-4b4e-8c4a-d1eeeee7108f