#!/bin/csh 
#$ -M cschaef6@nd.edu 
#$ -m abe
#$ -q gpu@@joshi
#$ -l gpu_card=1
#$ -N fl_test_checkpoint_206b224c-20c8-41a3-884b-400d8a6b6677_0
#$ -o ./logs/output_fl_test_fl_test_checkpoint_206b224c-20c8-41a3-884b-400d8a6b6677_0.txt
#$ -e ./logs/error_fl_test_fl_test_checkpoint_206b224c-20c8-41a3-884b-400d8a6b6677_0.txt
module load python
setenv OMP_NUM_THREADS $NSLOTS
python test.py --checkpoint 206b224c-20c8-41a3-884b-400d8a6b6677
