#!/bin/csh 
#$ -M cschaef6@nd.edu 
#$ -m abe
#$ -q gpu@@joshi
#$ -l gpu_card=1
#$ -N fl_test_checkpoint_f80d7f4a-0a32-4b5a-a2fe-380d9e9c0dae_0
#$ -o ./logs/output_fl_test_fl_test_checkpoint_f80d7f4a-0a32-4b5a-a2fe-380d9e9c0dae_0.txt
#$ -e ./logs/error_fl_test_fl_test_checkpoint_f80d7f4a-0a32-4b5a-a2fe-380d9e9c0dae_0.txt
module load python
setenv OMP_NUM_THREADS $NSLOTS
python test.py --checkpoint f80d7f4a-0a32-4b5a-a2fe-380d9e9c0dae