#!/bin/csh 
#$ -M cschaef6@nd.edu 
#$ -m abe
#$ -q gpu@@joshi
#$ -l gpu_card=1
#$ -N fl_test_checkpoint_4dc5d819-c5a8-445e-aac3-db6cf90e484c_0
#$ -o ./logs/output_fl_test_fl_test_checkpoint_4dc5d819-c5a8-445e-aac3-db6cf90e484c_0.txt
#$ -e ./logs/error_fl_test_fl_test_checkpoint_4dc5d819-c5a8-445e-aac3-db6cf90e484c_0.txt
module load python
setenv OMP_NUM_THREADS $NSLOTS
python test.py --checkpoint 4dc5d819-c5a8-445e-aac3-db6cf90e484c
