#!/bin/csh 
#$ -M cschaef6@nd.edu 
#$ -m abe
#$ -q gpu@@joshi
#$ -l gpu_card=1
#$ -N fl_test_checkpoint_f55bbde6-98ff-4fa0-be2b-ddaf6de7ac1c_0
#$ -o ./logs/output_fl_test_fl_test_checkpoint_f55bbde6-98ff-4fa0-be2b-ddaf6de7ac1c_0.txt
#$ -e ./logs/error_fl_test_fl_test_checkpoint_f55bbde6-98ff-4fa0-be2b-ddaf6de7ac1c_0.txt
module load python
setenv OMP_NUM_THREADS $NSLOTS
python test.py --checkpoint f55bbde6-98ff-4fa0-be2b-ddaf6de7ac1c
