#!/bin/csh 
#$ -M cschaef6@nd.edu 
#$ -m abe
#$ -q gpu@qa-rtx6k-041.crc.nd.edu
#$ -l gpu_card=1
#$ -N NoSelfsupervision_self-supervision_False_2
#$ -o ./logs/output_NoSelfsupervision_NoSelfsupervision_self-supervision_False_2.txt
#$ -e ./logs/error_NoSelfsupervision_NoSelfsupervision_self-supervision_False_2.txt
module load python
setenv OMP_NUM_THREADS $NSLOTS
python train.py --self-supervision False
